version: '3.4'

services:
  travis:
    image: roeldev/php-cli:${PHP_TAG}-${IMAGE_TAG}
    build:
      context: .
      args:
        PHP_VERSION: "${PHP_VERSION}"

  local:
    image: roeldev/php-cli:local
    container_name: php-cli
    build:
      context: .
      args:
        PHP_VERSION: "7.1"
    environment:
      - VERBOSE_INIT=true
